version: "3.7"
services:
    db:
        image: mariadb:10.5.8
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
          - "3306:3306"
        environment:
          MYSQL_DATABASE: laravel_web
          MYSQL_ROOT_PASSWORD: 123456
          SERVICE_TAGS: dev
          SERVICE_NAME: mysql
        volumes:
          - ./storage:/var/lib/mysql
networks:
    default:
        external: false
        name: app-network
